### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by ewlarson** [jhu-library-applications/geoblacklight#3]
Add the ExceptionNotification gem to capture application errors:
https://github.com/smartinez87/exception_notification

**Comment by ewlarson** [comment]
Targeting Slack as the potential notification channel.

**Comment by fackrellj** [comment]
@little9 @ewlarson should I go ahead and pull the exception notifications out and create a new issue to add Signal or App Signal?

**Comment by ewlarson** [comment]
Yes! Let's remove this gem in favor of the third party tools.
