### ISSUE TITLE
JHU Aardvark Fixtures

### ISSUE THREAD

**Issue by ewlarson** [jhu-library-applications/geoblacklight#67]
Make JHU fixtures.

**Comment by mjanowiecki** [comment]
[fixtures.zip](https://github.com/jhu-library-applications/geoblacklight/files/6365947/fixtures.zip)

**Comment by mjanowiecki** [comment]
[fixtures2.zip](https://github.com/jhu-library-applications/geoblacklight/files/6366050/fixtures2.zip)
fixtures.zip has dateRange, while fixtures2.zip has indexYear. We were hoping to see the difference if possible ?

**Comment by ewlarson** [comment]
The first zip (fixtures.zip) indexes well. 👍 

I'll test run the fixtures2.zip now to see how it indexes. But! There won't be anything to see. The dateRange values will be in the index for querying, but they won't be in the interface for displaying. Hope that makes sense.

**Comment by ewlarson** [comment]
A few discussion items regarding metadata:

- [ ] Year field: gbl_indexYear_im or gbl_indexYear_i (GBL metadata decision)
- [ ] Date ranges: I recommend you add them if you can
- [ ] JSON file naming: hh:mm might make things difficult, I recommend a non-dated filename
- [ ] Relations: GBL currently uses the Settings.FIELDS.SOURCE field for parent/child relations
